# via https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images
# and https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration
name: Publish Docker image
on:
  push:
    branches:
      - latest
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com # will need to become ghcr.io eventually
          repository: arduino-ci/action/ubuntu  # has to match organization and repo name, also has to be lowercase
          tag_with_ref: true
