---
name: Hadolint

on: [pull_request]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          # ignore rule about pinning packages -- we always want the latest!
          # otherwise when security release come out, the action breaks :(
          hadolint_ignore: DL3008
